server:
  port: 8083

spring:  application:    name: HYSTRIX-DASHBOARD-SERVICE

eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

hystrix:  dashboard:    proxy-stream-allow-list: "*"